### ISSUE TITLE
b[:*,:-,:-] can cause a crush.

### ISSUE THREAD

**Issue by kojix2** [ruby-numo/narray#33]
```ruby
require 'numo/narray'
a = Numo::Int32.ones(5,5,3)
b = Numo::Int32.new(5,5).fill(2)
p a * b[:*,:*,:-]

# p b[:*,:-,:-]  # [BUG] Segmentation fault
```
I do not know the correct behavior of this idiom. But it can cause a crush.

**Comment by masa16** [comment]
fixed in https://github.com/ruby-numo/narray/commit/47becc37538ea67be969f75a73aff3fb6e0e9b84
```
k.rb:6:in `[]': # of index(=1) should be equal to ndim(=2) (IndexError)
	from k.rb:6:in `<main>'
```

**Comment by kojix2** [comment]
Thank you!
