### ISSUE TITLE
Indexing or slicing narray with narray get somewhere else.

### ISSUE THREAD

**Issue by kojix2** [ruby-numo/narray#37]
Step to reproduce

```ruby
require 'numo/narray'
include Numo

a = UInt8[0]
# => Numo::UInt8#shape=[1]
# [0]

b = UInt8[1]
# => Numo::UInt8#shape=[1]
# [1]

a[b]
# => Numo::UInt8(view)#shape=[1]
# [103]
```

Expected behavior
```
IndexError: index=1 out of shape[0]=1
```

**Comment by masa16** [comment]
Fixed: https://github.com/ruby-numo/narray/commit/3716bb83cbd1a5579a687291b76836340cd9ca08
```ruby
require 'numo/narray'
include Numo

p a = UInt8[0]
# => Numo::UInt8#shape=[1]
# [0]

p b = UInt8[1]
# => Numo::UInt8#shape=[1]
# [1]

p a[b]
# t.rb:12:in `[]': index=1 out of shape[0]=1 (IndexError)
# 	from t.rb:12:in `<main>'
```

Thank you for reporting!
