### ISSUE TITLE
segmentation fault when empty shape ([]) NArray calls each_with_index.

### ISSUE THREAD

**Issue by naitoh** [ruby-numo/narray#69]
Hi, Segmentation fault occurs in the following code.

    require "numo/narray"
    Numo::DFloat.new.seq(1).each_with_index {}

Crash Report

    t.rb:2: [BUG] Segmentation fault at 0x00000000000001
    ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    
    -- Crash Report log information --------------------------------------------
       See Crash Report log file under the one of following:                    
         * ~/Library/Logs/DiagnosticReports                                     
         * /Library/Logs/DiagnosticReports                                      
       for more details.                                                        
    Don't forget to include the above Crash Report log file in bug reports.     
    
    -- Control frame information -----------------------------------------------
    c:0003 p:---- s:0010 e:000009 CFUNC  :each_with_index
    c:0002 p:0031 s:0006 e:000005 EVAL   t.rb:2 [FINISH]
    c:0001 p:0000 s:0003 E:0015b0 (none) [FINISH]
    
    -- Ruby level backtrace information ----------------------------------------
    t.rb:2:in `<main>'
    t.rb:2:in `each_with_index'
   
    -- Machine register context ------------------------------------------------
     rax: 0x98a7b29f54e80039 rbx: 0x00007fff525e9358 rcx: 0x0000000022220021
     rdx: 0x000000010d916068 rdi: 0x000000010d916068 rsi: 0x000000010d916068
     rbp: 0x00007fff525e8fb0 rsp: 0x00007fff525e8f60  r8: 0x00007fbb160b3c80
      r9: 0x000000010da15f70 r10: 0x0000000000000000 r11: 0x0000000000000000
     r12: 0x00007fff525e8f60 r13: 0x0000000000000000 r14: 0x0000000000000000
     r15: 0x00007fff525e91b0 rip: 0x0000000000000001 rfl: 0x0000000000010246
    
    -- C level backtrace information -------------------------------------------
     Killed: 9

Versions of ruby and numo::narray are

    $ gem list --local numo-narray
     
    *** LOCAL GEMS ***
    
    numo-narray (0.9.0.9)

    $ ruby -v
    ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

Regards.

**Comment by naitoh** [comment]
$ gem list --local numo-narray
     *** LOCAL GEMS ***
     numo-narray (0.9.1.0)

I confirmed.
Thank you bug fix.

     > require "numo/narray"
     => true
     > Numo::DFloat.new.seq(1).each_with_index {}
     => Numo::DFloat#shape=[]
     1
